//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAjoutProduitWCF.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap/", ConfigurationName="ServiceReference.ConsommerProduitWebService")]
    public interface ConsommerProduitWebService {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/ConsommerProduitWebService/inscrireProduitRequest", ReplyAction="http://soap/ConsommerProduitWebService/inscrireProduitResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientAjoutProduitWCF.ServiceReference.inscrireProduitResponse inscrireProduit(ClientAjoutProduitWCF.ServiceReference.inscrireProduitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/ConsommerProduitWebService/inscrireProduitRequest", ReplyAction="http://soap/ConsommerProduitWebService/inscrireProduitResponse")]
        System.Threading.Tasks.Task<ClientAjoutProduitWCF.ServiceReference.inscrireProduitResponse> inscrireProduitAsync(ClientAjoutProduitWCF.ServiceReference.inscrireProduitRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/ConsommerProduitWebService/consommerProduitsRequest", ReplyAction="http://soap/ConsommerProduitWebService/consommerProduitsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientAjoutProduitWCF.ServiceReference.consommerProduitsResponse consommerProduits(ClientAjoutProduitWCF.ServiceReference.consommerProduitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/ConsommerProduitWebService/consommerProduitsRequest", ReplyAction="http://soap/ConsommerProduitWebService/consommerProduitsResponse")]
        System.Threading.Tasks.Task<ClientAjoutProduitWCF.ServiceReference.consommerProduitsResponse> consommerProduitsAsync(ClientAjoutProduitWCF.ServiceReference.consommerProduitsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/")]
    public partial class produit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idProdField;
        
        private string nomProdField;
        
        private double prixProdField;
        
        private int qtyProdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idProd {
            get {
                return this.idProdField;
            }
            set {
                this.idProdField = value;
                this.RaisePropertyChanged("idProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nomProd {
            get {
                return this.nomProdField;
            }
            set {
                this.nomProdField = value;
                this.RaisePropertyChanged("nomProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double prixProd {
            get {
                return this.prixProdField;
            }
            set {
                this.prixProdField = value;
                this.RaisePropertyChanged("prixProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int qtyProd {
            get {
                return this.qtyProdField;
            }
            set {
                this.qtyProdField = value;
                this.RaisePropertyChanged("qtyProd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inscrireProduit", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class inscrireProduitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientAjoutProduitWCF.ServiceReference.produit Produit;
        
        public inscrireProduitRequest() {
        }
        
        public inscrireProduitRequest(ClientAjoutProduitWCF.ServiceReference.produit Produit) {
            this.Produit = Produit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inscrireProduitResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class inscrireProduitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public inscrireProduitResponse() {
        }
        
        public inscrireProduitResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consommerProduits", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class consommerProduitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int qtyProd;
        
        public consommerProduitsRequest() {
        }
        
        public consommerProduitsRequest(int idProd, int qtyProd) {
            this.idProd = idProd;
            this.qtyProd = qtyProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consommerProduitsResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class consommerProduitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public consommerProduitsResponse() {
        }
        
        public consommerProduitsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsommerProduitWebServiceChannel : ClientAjoutProduitWCF.ServiceReference.ConsommerProduitWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsommerProduitWebServiceClient : System.ServiceModel.ClientBase<ClientAjoutProduitWCF.ServiceReference.ConsommerProduitWebService>, ClientAjoutProduitWCF.ServiceReference.ConsommerProduitWebService {
        
        public ConsommerProduitWebServiceClient() {
        }
        
        public ConsommerProduitWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsommerProduitWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsommerProduitWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsommerProduitWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAjoutProduitWCF.ServiceReference.inscrireProduitResponse ClientAjoutProduitWCF.ServiceReference.ConsommerProduitWebService.inscrireProduit(ClientAjoutProduitWCF.ServiceReference.inscrireProduitRequest request) {
            return base.Channel.inscrireProduit(request);
        }
        
        public bool inscrireProduit(ClientAjoutProduitWCF.ServiceReference.produit Produit) {
            ClientAjoutProduitWCF.ServiceReference.inscrireProduitRequest inValue = new ClientAjoutProduitWCF.ServiceReference.inscrireProduitRequest();
            inValue.Produit = Produit;
            ClientAjoutProduitWCF.ServiceReference.inscrireProduitResponse retVal = ((ClientAjoutProduitWCF.ServiceReference.ConsommerProduitWebService)(this)).inscrireProduit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientAjoutProduitWCF.ServiceReference.inscrireProduitResponse> ClientAjoutProduitWCF.ServiceReference.ConsommerProduitWebService.inscrireProduitAsync(ClientAjoutProduitWCF.ServiceReference.inscrireProduitRequest request) {
            return base.Channel.inscrireProduitAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientAjoutProduitWCF.ServiceReference.inscrireProduitResponse> inscrireProduitAsync(ClientAjoutProduitWCF.ServiceReference.produit Produit) {
            ClientAjoutProduitWCF.ServiceReference.inscrireProduitRequest inValue = new ClientAjoutProduitWCF.ServiceReference.inscrireProduitRequest();
            inValue.Produit = Produit;
            return ((ClientAjoutProduitWCF.ServiceReference.ConsommerProduitWebService)(this)).inscrireProduitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAjoutProduitWCF.ServiceReference.consommerProduitsResponse ClientAjoutProduitWCF.ServiceReference.ConsommerProduitWebService.consommerProduits(ClientAjoutProduitWCF.ServiceReference.consommerProduitsRequest request) {
            return base.Channel.consommerProduits(request);
        }
        
        public string consommerProduits(int idProd, int qtyProd) {
            ClientAjoutProduitWCF.ServiceReference.consommerProduitsRequest inValue = new ClientAjoutProduitWCF.ServiceReference.consommerProduitsRequest();
            inValue.idProd = idProd;
            inValue.qtyProd = qtyProd;
            ClientAjoutProduitWCF.ServiceReference.consommerProduitsResponse retVal = ((ClientAjoutProduitWCF.ServiceReference.ConsommerProduitWebService)(this)).consommerProduits(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientAjoutProduitWCF.ServiceReference.consommerProduitsResponse> ClientAjoutProduitWCF.ServiceReference.ConsommerProduitWebService.consommerProduitsAsync(ClientAjoutProduitWCF.ServiceReference.consommerProduitsRequest request) {
            return base.Channel.consommerProduitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientAjoutProduitWCF.ServiceReference.consommerProduitsResponse> consommerProduitsAsync(int idProd, int qtyProd) {
            ClientAjoutProduitWCF.ServiceReference.consommerProduitsRequest inValue = new ClientAjoutProduitWCF.ServiceReference.consommerProduitsRequest();
            inValue.idProd = idProd;
            inValue.qtyProd = qtyProd;
            return ((ClientAjoutProduitWCF.ServiceReference.ConsommerProduitWebService)(this)).consommerProduitsAsync(inValue);
        }
    }
}
