//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAjoutProduitWCF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap/", ConfigurationName="ServiceReference1.ConsommerProduitWebService")]
    public interface ConsommerProduitWebService {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément return de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/ConsommerProduitWebService/consommerProduitsRequest", ReplyAction="http://soap/ConsommerProduitWebService/consommerProduitsResponse")]
        ClientAjoutProduitWCF.ServiceReference1.consommerProduitsResponse consommerProduits(ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/ConsommerProduitWebService/consommerProduitsRequest", ReplyAction="http://soap/ConsommerProduitWebService/consommerProduitsResponse")]
        System.Threading.Tasks.Task<ClientAjoutProduitWCF.ServiceReference1.consommerProduitsResponse> consommerProduitsAsync(ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consommerProduitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consommerProduits", Namespace="http://soap/", Order=0)]
        public ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequestBody Body;
        
        public consommerProduitsRequest() {
        }
        
        public consommerProduitsRequest(ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consommerProduitsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int nombre;
        
        public consommerProduitsRequestBody() {
        }
        
        public consommerProduitsRequestBody(int idProd, int nombre) {
            this.idProd = idProd;
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consommerProduitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consommerProduitsResponse", Namespace="http://soap/", Order=0)]
        public ClientAjoutProduitWCF.ServiceReference1.consommerProduitsResponseBody Body;
        
        public consommerProduitsResponse() {
        }
        
        public consommerProduitsResponse(ClientAjoutProduitWCF.ServiceReference1.consommerProduitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consommerProduitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public consommerProduitsResponseBody() {
        }
        
        public consommerProduitsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsommerProduitWebServiceChannel : ClientAjoutProduitWCF.ServiceReference1.ConsommerProduitWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsommerProduitWebServiceClient : System.ServiceModel.ClientBase<ClientAjoutProduitWCF.ServiceReference1.ConsommerProduitWebService>, ClientAjoutProduitWCF.ServiceReference1.ConsommerProduitWebService {
        
        public ConsommerProduitWebServiceClient() {
        }
        
        public ConsommerProduitWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsommerProduitWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsommerProduitWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsommerProduitWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAjoutProduitWCF.ServiceReference1.consommerProduitsResponse ClientAjoutProduitWCF.ServiceReference1.ConsommerProduitWebService.consommerProduits(ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequest request) {
            return base.Channel.consommerProduits(request);
        }
        
        public string consommerProduits(int idProd, int nombre) {
            ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequest inValue = new ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequest();
            inValue.Body = new ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequestBody();
            inValue.Body.idProd = idProd;
            inValue.Body.nombre = nombre;
            ClientAjoutProduitWCF.ServiceReference1.consommerProduitsResponse retVal = ((ClientAjoutProduitWCF.ServiceReference1.ConsommerProduitWebService)(this)).consommerProduits(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientAjoutProduitWCF.ServiceReference1.consommerProduitsResponse> ClientAjoutProduitWCF.ServiceReference1.ConsommerProduitWebService.consommerProduitsAsync(ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequest request) {
            return base.Channel.consommerProduitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientAjoutProduitWCF.ServiceReference1.consommerProduitsResponse> consommerProduitsAsync(int idProd, int nombre) {
            ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequest inValue = new ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequest();
            inValue.Body = new ClientAjoutProduitWCF.ServiceReference1.consommerProduitsRequestBody();
            inValue.Body.idProd = idProd;
            inValue.Body.nombre = nombre;
            return ((ClientAjoutProduitWCF.ServiceReference1.ConsommerProduitWebService)(this)).consommerProduitsAsync(inValue);
        }
    }
}
